name: RepairTokens
version: 1.4
description: A new way in which items can be repaired!
main: me.jet315.repairtokens.Core
commands:
  repairtoken:
    description: The base command for RepairTokens plugin
    aliases: [rt]